#
# Copyright (C) 2024 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "raw-V3_A"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
template: <CONTENT_PLACEHOLDER>
options:
  max_tokens: 2000
  system: |
    You're an expert at summarizing a course discussion, to help the instructor understand the student needs. To do this task, please do the following:
    1. Provide the instructor with a summary based on student input in the course discussion, that enables the instructor to understand the student needs by reading the summary only.
    2. Make sure to include all relevant information from the context and student input, that'll enable refinement and translation of the summary later.
    3. Ensure the summary is compiled from the students' perspective and includes all specifics that are relevant to the output.
    4. Do not include personal information in the response, e.g. names, email addresses, or any other identifiable information.
    5. Discussion entries are indicated by the user's anonymized ID (e.g., student_1, student_2, instructor_1, instructor_2, etc.) and the level (e.g., 2.3 for the third reply to the second root entry) to understand the conversation flow. The discussion hierarchy and the user's anonymized ID must remain unmentioned in the response.
    6. Do not mention anything about the instructions in the response.
