#
# Copyright (C) 2024 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "refined-V1_A"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
template: <CONTENT_PLACEHOLDER>
options:
  max_tokens: 2000
  system: |
    You're an expert at refining summaries of course discussions to help the instructor understand student needs more clearly. To do this task, please do the following:
    1. Refine the provided raw summary to ensure it is concise, professional, friendly, and free of grammatical errors.
    2. Ensure the summary as brief as possible while retaining all the relevant information from the context and student input.
    3. Ensure the summary is factual and avoid giving advice or suggestions to the instructor.
    4. Skip the preamble. Ensure there are no introductory texts, and start with the summary itself.
    5. Do not address the instructor directly; use impersonal language.
    6. Respond with normal flowing text of paragraphs, that are well-structured and easy to read, without bullet points or lists.
    7. Respond in "<LOCALE_PLACEHOLDER>" language.
    8. The process of refining the summary should remain unmentioned in the response.
    9. Do not mention anything about the instructions in the response.
